<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>disable</Nullable>
        <RunPostBuildEvent>Always</RunPostBuildEvent>
        <LangVersion>14</LangVersion>
        <RootNamespace>ModPublisher</RootNamespace>
    </PropertyGroup>

    <PropertyGroup>
        <OutputPath>$(SPZ2_PERSISTENT)\mods\Mod Publisher</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <Reference Include="ShapezShifter">
            <HintPath>$(SPZ2_SHIFTER)</HintPath>
            <Private>False</Private>
        </Reference>
        <PackageReference Include="MonoMod.RuntimeDetour" Version="25.3.0"/>
        <Reference Include="SPZGameAssembly">
            <HintPath>$(SPZ2_PATH)\SPZGameAssembly.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="MainMenuAssembly">
            <HintPath>$(SPZ2_PATH)\MainMenuAssembly.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Unity.Core">
            <HintPath>$(SPZ2_PATH)\Unity.Core.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Content">
            <HintPath>$(SPZ2_PATH)\Game.Content.dll</HintPath>
            <Private>False</Private>
        </Reference>


        <Reference Include="Game.Content.Features">
            <HintPath>$(SPZ2_PATH)\Game.Content.Features.dll</HintPath>
            <Private>False</Private>
        </Reference>

        <Reference Include="Game.Core.Content">
            <HintPath>$(SPZ2_PATH)\Game.Core.Content.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Core.Map">
            <HintPath>$(SPZ2_PATH)\Game.Core.Map.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Core.Map.Layout">
            <HintPath>$(SPZ2_PATH)\Game.Core.Map.Layout.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Core.Map.Layout.Model">
            <HintPath>$(SPZ2_PATH)\Game.Core.Map.Layout.Model.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Core.Map.Model">
            <HintPath>$(SPZ2_PATH)\Game.Core.Map.Model.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Core.Simulation">
            <HintPath>$(SPZ2_PATH)\Game.Core.Simulation.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Core.Rendering">
            <HintPath>$(SPZ2_PATH)\Game.Core.Rendering.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.ImageConversionModule">
            <HintPath>$(SPZ2_PATH)\UnityEngine.ImageConversionModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestModule">
            <HintPath>$(SPZ2_PATH)\UnityEngine.UnityWebRequestModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestTextureModule">
            <HintPath>$(SPZ2_PATH)\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Unity.Mathematics">
            <HintPath>$(SPZ2_PATH)\Unity.Mathematics.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Core.Modding">
            <HintPath>$(SPZ2_PATH)\Game.Core.Modding.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Core.Localization">
            <HintPath>$(SPZ2_PATH)\Core.Localization.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Orchestration">
            <HintPath>$(SPZ2_PATH)\Game.Orchestration.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Core.Blueprint">
            <HintPath>$(SPZ2_PATH)\Game.Core.Blueprint.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Core.Blueprint.Exporter">
            <HintPath>$(SPZ2_PATH)\Game.Core.Blueprint.Exporter.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Core.Blueprint.Importer">
            <HintPath>$(SPZ2_PATH)\Game.Core.Blueprint.Importer.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Core.Blueprint.Serialization">
            <HintPath>$(SPZ2_PATH)\Game.Core.Blueprint.Serialization.dll</HintPath>
            <Private>False</Private>
        </Reference>

        <Reference Include="Game.Interaction">
            <HintPath>$(SPZ2_PATH)\Game.Interaction.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Core.Coordinates">
            <HintPath>$(SPZ2_PATH)\Game.Core.Coordinates.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Core">
            <HintPath>$(SPZ2_PATH)\Core.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Core">
            <HintPath>$(SPZ2_PATH)\Game.Core.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Core.Map.Simulation">
            <HintPath>$(SPZ2_PATH)\Game.Core.Map.Simulation.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Hud">
            <HintPath>$(SPZ2_PATH)\Game.Hud.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Hud.View">
            <HintPath>$(SPZ2_PATH)\Game.Hud.View.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Hud.View.Model">
            <HintPath>$(SPZ2_PATH)\Game.Hud.View.Model.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Modding">
            <HintPath>$(SPZ2_PATH)\Game.Modding.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(SPZ2_PATH)\UnityEngine.CoreModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine">
            <HintPath>$(SPZ2_PATH)\UnityEngine.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>$(SPZ2_PATH)\UnityEngine.UI.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>$(SPZ2_PATH)\UnityEngine.UI.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.UIElementsModule">
            <HintPath>$(SPZ2_PATH)\UnityEngine.UIElementsModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.UIModule">
            <HintPath>$(SPZ2_PATH)\UnityEngine.UIModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.AssetBundleModule">
            <HintPath>$(SPZ2_PATH)\UnityEngine.AssetBundleModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.AudioModule">
            <HintPath>$(SPZ2_PATH)\UnityEngine.AudioModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.VideoModule">
            <HintPath>$(SPZ2_PATH)\UnityEngine.VideoModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="DOTween">
            <HintPath>$(SPZ2_PATH)\DOTween.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="LeTai.Asset.TranslucentImage">
            <HintPath>$(SPZ2_PATH)\LeTai.Asset.TranslucentImage.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Unity.TextMeshPro">
            <HintPath>$(SPZ2_PATH)\Unity.TextMeshPro.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="SPZPluginsAssembly">
            <HintPath>$(SPZ2_PATH)\SPZPluginsAssembly.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Semver">
            <HintPath>$(SPZ2_PATH)\Semver.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Shapez2UILib">
            <HintPath>$(SPZ2_UILIB)</HintPath>
            <Private>False</Private>
        </Reference>

        <ProjectReference Include="..\SteamworksInteraction\SteamworksInteraction.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <PublicizeAll>true</PublicizeAll>
    </PropertyGroup>

    <ItemGroup>
        <DoNotPublicize Include="SPZGameAssembly:BeltLaneRenderingDefinition" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false"/>
        <DoNotPublicize Include="Game.Core.Coordinates" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false"/>
        <DoNotPublicize Include="SPZGameAssembly:BuildingDefinition" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false"/>
        <DoNotPublicize Include="Game.Orchestration:ParentToolbarElementData" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false"/>
    </ItemGroup>

    <PropertyGroup>
        <PublicizerClearCacheOnClean>true</PublicizerClearCacheOnClean>
    </PropertyGroup>

    <PropertyGroup>
        <PublicizerLogFilePath>logs/krafs</PublicizerLogFilePath>
    </PropertyGroup>

    <ItemGroup>
        <None Update="translations.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="manifest.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Resources/*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>